# Site settings
title: مطاردة الحقيقة
tag_text: مطاردة الحقيقة
description: Searching for the Truth amid the ruins of the Lies!
url: ""
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]